# Introduction to Pandas

- Pandas is an open source Python Library / Module providing high performance and data manipulation and Analysis Tool.
- The Traditional Python Programming does not contain any Module for Data Analysis and Now Python Programming uses Pandas as an anaysis tool.

# Installation of Pandas

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [3]:
print(pd.__version__)

2.1.4

# Data Structures used in Pandas

=>In Pandas programming, we can store the data in 2 types of Data structures. They are.

		a) Series
		b) DataFrame

# Series

In [1]:
lst = [10,20,30,40,50,60]

s = pd.Series(lst)

print(s,type(s))

NameError: name 'pd' is not defined

In [9]:
s = pd.Series([10,20,30,40,50,60])

print(s,type(s))

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64 <class 'pandas.core.series.Series'>

In [10]:
lst=(10,20,30,40,50,60)

s = pd.Series(lst,dtype=float)

print(s,type(s))

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
dtype: float64 <class 'pandas.core.series.Series'>

In [ ]:
s.shape

In [11]:
lst = [10,"Rossum",34.56,"Author"]

#print(lst)
#s = pd.Series(lst,index=[1,2,3,4])

s = pd.Series(lst,index=["Stno","Name","Marks","Desg"])

print(s,type(s))

Stno         10
Name     Rossum
Marks     34.56
Desg     Author
dtype: object <class 'pandas.core.series.Series'>

In [12]:
d1 = {"sub1":"Python","sub2":"Java","sub3":"Data Science","sub4":"ML"}
print(d1,type(d1))

{'sub1': 'Python', 'sub2': 'Java', 'sub3': 'Data Science', 'sub4': 'ML'} <class 'dict'>

In [13]:
d1.items()

dict_items([('sub1', 'Python'), ('sub2', 'Java'), ('sub3', 'Data Science'), ('sub4', 'ML')])

In [14]:
d1.keys()

dict_keys(['sub1', 'sub2', 'sub3', 'sub4'])

In [15]:
d1.values()

dict_values(['Python', 'Java', 'Data Science', 'ML'])

In [16]:
d1 = {"sub1":"Python","sub2":"Java","sub3":"Data Science","sub4":"ML"}

#print(d1)
s = pd.Series(d1)
print(s)

sub1          Python
sub2            Java
sub3    Data Science
sub4              ML
dtype: object

In [17]:
s['sub2']

'Java'

# DataFrame

=>A DataFrame is 2-Dimensional Data Structure to organize the data .
=>In Otherwords a DataFrame Organizes the data in the Tabular Format, which is nothing but Collection of Rows and Columns.

# Creating an object DataFrame by Using list / tuple

In [18]:
lst = [[10,20,30,40],[10,20,30,40],[10,20,30,40]]

df = pd.DataFrame(lst)
df.shape

print(df)

    0   1   2   3
0  10  20  30  40
1  10  20  30  40
2  10  20  30  40

In [19]:
lst = [[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]

df = pd.DataFrame(lst)

print(df)

    0    1
0  10   RS
1  20   JG
2  30  MCK
3  40  TRA

In [20]:
lst=[[10,'RS'],[20,'JG'],[30,'MCK'],[40,'TRA']]

df=pd.DataFrame(lst,columns=['Rno','Name'],index=[10,20,30,40])

print(df)

    Rno Name
10   10   RS
20   20   JG
30   30  MCK
40   40  TRA

In [21]:
tpl = ( ("Rossum",75), ("Gosling",85), ("Travis",65), ("Ritche",95),("MCKinney",60) )

df = pd.DataFrame(tpl, index=[1,2,3,4,5],columns=['Name','Age'])

print(df)

       Name  Age
1    Rossum   75
2   Gosling   85
3    Travis   65
4    Ritche   95
5  MCKinney   60

# Creating an object DataFrame by Using dict object

In [1]:
dictdata = {"Names":["Rossum","Gosling","Ritche","McKinney"],"Subjects":["Python","Java","C","Pandas"],"Ages":[65,80,85,55]  }
#dictdata.values()
print(dictdata)

{'Names': ['Rossum', 'Gosling', 'Ritche', 'McKinney'], 'Subjects': ['Python', 'Java', 'C', 'Pandas'], 'Ages': [65, 80, 85, 55]}

In [5]:
df = pd.DataFrame(dictdata)

print(df)

      Names Subjects  Ages
0    Rossum   Python    65
1   Gosling     Java    80
2    Ritche        C    85
3  McKinney   Pandas    55

In [6]:
df=pd.DataFrame(dictdata,index=[1,2,3,4])
print(df)

      Names Subjects  Ages
1    Rossum   Python    65
2   Gosling     Java    80
3    Ritche        C    85
4  McKinney   Pandas    55

# Creating an object DataFrame by Using Series object

In [10]:
l1 = [10,20,30,40]

sdata = pd.Series(l1)

print(type(sdata))

print(sdata)

<class 'pandas.core.series.Series'>
0    10
1    20
2    30
3    40
dtype: int64

In [11]:
df= pd.DataFrame(sdata, columns=["number"])

print(df)

   number
0      10
1      20
2      30
3      40

In [ ]:
df.shape

In [ ]:
type(df)

In [15]:
sdata = pd.Series([10,20,30,40])

df = pd.DataFrame(sdata)
print(df)

    0
0  10
1  20
2  30
3  40

In [ ]:
type(df)

In [20]:
d1 = {"totmark":[100,110,120,130],"ExtMarks":[80,75,65,90]}

df = pd.DataFrame(d1,index=[1,2,3,4])

df

   totmark  ExtMarks
1      100        80
2      110        75
3      120        65
4      130        90

In [21]:
df.columns

Index(['totmark', 'ExtMarks'], dtype='object')

# Adding new Column Name to Data Frame

In [22]:
# Add is a new column name
df['Add'] = df['totmark'] + df['ExtMarks']
df

   totmark  ExtMarks  Add
1      100        80  180
2      110        75  185
3      120        65  185
4      130        90  220

In [23]:
df['sub'] = df['totmark'] - df['ExtMarks']
df

   totmark  ExtMarks  Add  sub
1      100        80  180   20
2      110        75  185   35
3      120        65  185   55
4      130        90  220   40

In [24]:
# Roll_No1 is a new column
df['Roll_NO1'] = range(1,5)
df

   totmark  ExtMarks  Add  sub  Roll_NO1
1      100        80  180   20         1
2      110        75  185   35         2
3      120        65  185   55         3
4      130        90  220   40         4

In [25]:
# changing the column order
df = df[['Roll_NO1','totmark','ExtMarks','Add','sub']]
df

   Roll_NO1  totmark  ExtMarks  Add  sub
1         1      100        80  180   20
2         2      110        75  185   35
3         3      120        65  185   55
4         4      130        90  220   40

In [26]:
import numpy as np
# Adding NULL values to a new column called name
df['name'] = np.nan
df

C:\Users\user\AppData\Local\Temp\ipykernel_7732\4071656422.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = np.nan

   Roll_NO1  totmark  ExtMarks  Add  sub  name
1         1      100        80  180   20   NaN
2         2      110        75  185   35   NaN
3         3      120        65  185   55   NaN
4         4      130        90  220   40   NaN

In [36]:
# Updating the value using the column name & index no

df['name'][3],df['name'][1] = "Abishek",'ram'
df['name'][2]='raju'
df

C:\Users\user\AppData\Local\Temp\ipykernel_7732\2771660787.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][3],df['name'][1] = "Abishek",'ram'
C:\Users\user\AppData\Local\Temp\ipykernel_7732\2771660787.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][3],df['name'][1] = "Abishek",'ram'
C:\Users\user\AppData\Local\Temp\ipykernel_7732\2771660787.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'][2]='raju'

   Roll_NO1  totmark  ExtMarks  Add  sub     name
1         1      100        80  180   20      ram
2         2      110        75  185   35     raju
3         3      120        65  185   55  Abishek
4         4      130        90  220   40      NaN

In [37]:
df['sub'] = df['totmark'] - df['ExtMarks']
df

C:\Users\user\AppData\Local\Temp\ipykernel_7732\402095862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sub'] = df['totmark'] - df['ExtMarks']

   Roll_NO1  totmark  ExtMarks  Add  sub     name
1         1      100        80  180   20      ram
2         2      110        75  185   35     raju
3         3      120        65  185   55  Abishek
4         4      130        90  220   40      NaN

In [38]:
df.columns

Index(['Roll_NO1', 'totmark', 'ExtMarks', 'Add', 'sub', 'name'], dtype='object')

# Removing Column Name from Data Frame

In [39]:
# columns

df = df.drop(columns='name')  # column name 
df

   Roll_NO1  totmark  ExtMarks  Add  sub
1         1      100        80  180   20
2         2      110        75  185   35
3         3      120        65  185   55
4         4      130        90  220   40

In [40]:
# remove a row

df = df.drop(3) # index number

In [41]:
df

   Roll_NO1  totmark  ExtMarks  Add  sub
1         1      100        80  180   20
2         2      110        75  185   35
4         4      130        90  220   40

In [42]:
# change the value of specific row of any column


df['totmark'][2] = 150

df

   Roll_NO1  totmark  ExtMarks  Add  sub
1         1      100        80  180   20
2         2      150        75  185   35
4         4      130        90  220   40

In [44]:
df = df.drop(2)
df

   Roll_NO1  totmark  ExtMarks  Add  sub
1         1      100        80  180   20
4         4      130        90  220   40

In [45]:
# delete mutiple Columns

df = df.drop(columns=['Add','sub'])
df

   Roll_NO1  totmark  ExtMarks
1         1      100        80
4         4      130        90

In [ ]:
df = df.drop(columns='ExtMarks')

In [ ]:
df

# sorting the dataframe data

In [46]:
df = df.sort_values(["totmark"] )
df

   Roll_NO1  totmark  ExtMarks
1         1      100        80
4         4      130        90

In [47]:
df = df.sort_values(["totmark"] ,ascending=False) # descending order = ascending = False
df

   Roll_NO1  totmark  ExtMarks
4         4      130        90
1         1      100        80

In [52]:
df.to_csv('studentdata.excel')

In [49]:
import os
os.getcwd()

'C:\\Users\\user\\Desktop\\Python basics - S\\Python basics - S'

In [ ]:
total_marks,sub
100,python
20,c

In [64]:
#city = df['city'] & ['id']
city = df[['city']]
city

           city
0     Bangalore
1    Chandigarh
2         Delhi
3        Mumbai
4       Kolkata
..          ...
811       Dubai
812       Dubai
813   Abu Dhabi
814   Abu Dhabi
815       Dubai

[816 rows x 1 columns]

In [67]:
df = df.drop(columns=['umpire1', 'umpire2'])
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [68]:
city1 = city.T # Transpose

city1

,0,1,2,3,4,5,6,7,8,9,...,806,807,808,809,810,811,812,813,814,815
city,Bangalore,Chandigarh,Delhi,Mumbai,Kolkata,Jaipur,Hyderabad,Chennai,Hyderabad,Chandigarh,...,Dubai,Dubai,Dubai,Abu Dhabi,Dubai,Dubai,Dubai,Abu Dhabi,Abu Dhabi,Dubai

In [ ]:
city2 = city1.T

city2

In [69]:
df['player_of_match']

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [70]:
df.head(10)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN
5,335987,Jaipur,2008-04-21,SR Watson,Sawai Mansingh Stadium,0,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,N,NaN
6,335988,Hyderabad,2008-04-22,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,N,NaN
7,335989,Chennai,2008-04-23,ML Hayden,"MA Chidambaram Stadium, Chepauk",0,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,N,NaN
8,335990,Hyderabad,2008-04-24,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",0,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,N,NaN
9,335991,Chandigarh,2008-04-25,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,N,NaN

In [71]:
df.head(1)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN

In [72]:
df.tail()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [73]:
df.tail(10)

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
806,1216542,Dubai,2020-10-08,JM Bairstow,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,N,NaN
807,1216543,Dubai,2020-10-14,A Nortje,Dubai International Cricket Stadium,0,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,N,NaN
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN
809,1216545,Abu Dhabi,2020-09-26,Shubman Gill,Sheikh Zayed Stadium,0,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,7.0,N,NaN
810,1216546,Dubai,2020-10-20,S Dhawan,Dubai International Cricket Stadium,0,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,Kings XI Punjab,wickets,5.0,N,NaN
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [74]:
# rows, columns

df.shape

(816, 15)

In [75]:
# all columns names

df.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method'],
      dtype='object')

In [76]:
# to check datatype of each column

df.dtypes

id                   int64
city                object
date                object
player_of_match     object
venue               object
neutral_venue        int64
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result              object
result_margin      float64
eliminator          object
method              object
dtype: object

In [77]:
#astype - it is used to change from one datatype to another

df['id'] = df['id'].astype(int)  # astype()

df.dtypes

8 4 2 1
0 0 0 0

id                   int32
city                object
date                object
player_of_match     object
venue               object
neutral_venue        int64
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result              object
result_margin      float64
eliminator          object
method              object
dtype: object

In [78]:
# information of all the columns, like column name, dtype,rows

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int32
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
dtypes: float64(1), int32(1), int64(1), object(12)
memory usage: 92.6+ KB

In [79]:
df.describe()

                 id  neutral_venue  result_margin
count  8.160000e+02     816.000000     799.000000
mean   7.563496e+05       0.094363      17.321652
std    3.058943e+05       0.292512      22.068427
min    3.359820e+05       0.000000       1.000000
25%    5.012278e+05       0.000000       6.000000
50%    7.292980e+05       0.000000       8.000000
75%    1.082626e+06       0.000000      19.500000
max    1.237181e+06       1.000000     146.000000

In [ ]:
df = df.drop(columns=['umpire1', 'umpire2'])
df

In [80]:
df[df['eliminator'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
241,501265,Delhi,2011-05-21,NaN,Feroz Shah Kotla,0,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,NaN,NaN,NaN,NaN
486,829763,Bangalore,2015-04-29,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN
511,829813,Bangalore,2015-05-17,NaN,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,NaN,NaN,NaN,NaN
744,1178424,Bengaluru,2019-04-30,NaN,M.Chinnaswamy Stadium,0,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,NaN,NaN,NaN,NaN

In [81]:
df[df['city'].isnull()]

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
399,729281,NaN,2014-04-17,YS Chahal,Sharjah Cricket Stadium,1,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,N,NaN
402,729287,NaN,2014-04-19,PA Patel,Dubai International Cricket Stadium,1,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN
403,729289,NaN,2014-04-19,JP Duminy,Dubai International Cricket Stadium,1,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,N,NaN
404,729291,NaN,2014-04-20,GJ Maxwell,Sharjah Cricket Stadium,1,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,N,NaN
406,729295,NaN,2014-04-22,GJ Maxwell,Sharjah Cricket Stadium,1,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,N,NaN
407,729297,NaN,2014-04-23,RA Jadeja,Dubai International Cricket Stadium,1,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,N,NaN
408,729299,NaN,2014-04-24,CA Lynn,Sharjah Cricket Stadium,1,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,N,NaN
409,729301,NaN,2014-04-25,AJ Finch,Dubai International Cricket Stadium,1,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,N,NaN
410,729303,NaN,2014-04-25,MM Sharma,Dubai International Cricket Stadium,1,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,N,NaN
413,729309,NaN,2014-04-27,M Vijay,Sharjah Cricket Stadium,1,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,N,NaN
414,729311,NaN,2014-04-27,DR Smith,Sharjah Cricket Stadium,1,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,N,NaN
415,729313,NaN,2014-04-28,Sandeep Sharma,Dubai International Cricket Stadium,1,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,N,NaN
417,729317,NaN,2014-04-30,B Kumar,Dubai International Cricket Stadium,1,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,N,NaN

In [82]:
df.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
dtype: int64

In [83]:
df['eliminator'].isnull().sum()

4

In [84]:
# to find null values

df.isnull().sum()

id                   0
city                13
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
dtype: int64

In [87]:
df['city'] = df['city'].fillna('Dubai')
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [88]:
df['player_of_match']

0         BB McCullum
1          MEK Hussey
2         MF Maharoof
3          MV Boucher
4           DJ Hussey
            ...
811    AB de Villiers
812         JJ Bumrah
813     KS Williamson
814        MP Stoinis
815          TA Boult
Name: player_of_match, Length: 816, dtype: object

In [89]:
# count of each venues

df['venue'].value_counts()

venue
Eden Gardens                                            77
Feroz Shah Kotla                                        74
Wankhede Stadium                                        73
M Chinnaswamy Stadium                                   65
Rajiv Gandhi International Stadium, Uppal               64
MA Chidambaram Stadium, Chepauk                         57
Sawai Mansingh Stadium                                  47
Punjab Cricket Association Stadium, Mohali              35
Dubai International Cricket Stadium                     33
Sheikh Zayed Stadium                                    29
Punjab Cricket Association IS Bindra Stadium, Mohali    21
Maharashtra Cricket Association Stadium                 21
Sharjah Cricket Stadium                                 18
Dr DY Patil Sports Academy                              17
Subrata Roy Sahara Stadium                              17
M.Chinnaswamy Stadium                                   15
Kingsmead                                               15
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     13
Sardar Patel Stadium, Motera                            12
SuperSport Park                                         12
Brabourne Stadium                                       11
Saurashtra Cricket Association Stadium                  10
Himachal Pradesh Cricket Association Stadium             9
Holkar Cricket Stadium                                   9
New Wanderers Stadium                                    8
Barabati Stadium                                         7
Newlands                                                 7
St George's Park                                         7
JSCA International Stadium Complex                       7
Shaheed Veer Narayan Singh International Stadium         6
Nehru Stadium                                            5
Green Park                                               4
Buffalo Park                                             3
Vidarbha Cricket Association Stadium, Jamtha             3
De Beers Diamond Oval                                    3
OUTsurance Oval                                          2
Name: count, dtype: int64

In [ ]:
# replace

df['venue'] = df['venue'].replace('M.Chinnaswamy Stadium','M Chinnaswamy Stadium')

In [90]:
df['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket Stadium',
       'Maharashtra Cricket Association Stadium',
       'Punjab Cricket Association IS Bindra Stadium, Mohali',
       'Saurashtra Cricket Association Stadium', 'Green Park',
       'M.Chinnaswamy Stadium'], dtype=object)

In [91]:
df[df['venue'] == 'Dubai International Cricket Stadium']

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method
402,729287,Dubai,2014-04-19,PA Patel,Dubai International Cricket Stadium,1,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,N,NaN
403,729289,Dubai,2014-04-19,JP Duminy,Dubai International Cricket Stadium,1,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,N,NaN
407,729297,Dubai,2014-04-23,RA Jadeja,Dubai International Cricket Stadium,1,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,N,NaN
409,729301,Dubai,2014-04-25,AJ Finch,Dubai International Cricket Stadium,1,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,N,NaN
410,729303,Dubai,2014-04-25,MM Sharma,Dubai International Cricket Stadium,1,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,N,NaN
415,729313,Dubai,2014-04-28,Sandeep Sharma,Dubai International Cricket Stadium,1,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,N,NaN
417,729317,Dubai,2014-04-30,B Kumar,Dubai International Cricket Stadium,1,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,N,NaN
757,1216493,Dubai,2020-09-20,MP Stoinis,Dubai International Cricket Stadium,0,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,Y,NaN
762,1216498,Dubai,2020-10-24,CJ Jordan,Dubai International Cricket Stadium,0,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,12.0,N,NaN
768,1216504,Dubai,2020-09-30,Shivam Mavi,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,37.0,N,NaN
771,1216507,Dubai,2020-10-11,R Tewatia,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,5.0,N,NaN
774,1216510,Dubai,2020-09-24,KL Rahul,Dubai International Cricket Stadium,0,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kings XI Punjab,runs,97.0,N,NaN
777,1216513,Dubai,2020-10-04,SR Watson,Dubai International Cricket Stadium,0,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,N,NaN
780,1216516,Dubai,2020-10-02,PK Garg,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,7.0,N,NaN
781,1216517,Dubai,2020-10-18,KL Rahul,Dubai International Cricket Stadium,0,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,Y,NaN
782,1216518,Dubai,2020-10-22,MK Pandey,Dubai International Cricket Stadium,0,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,N,NaN
783,1216519,Dubai,2020-10-05,AR Patel,Dubai International Cricket Stadium,0,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Capitals,runs,59.0,N,NaN
786,1216522,Dubai,2020-10-17,AB de Villiers,Dubai International Cricket Stadium,0,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,N,NaN
788,1216524,Dubai,2020-10-27,WP Saha,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,88.0,N,NaN
789,1216525,Dubai,2020-10-10,V Kohli,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,N,NaN
792,1216528,Dubai,2020-10-13,RA Jadeja,Dubai International Cricket Stadium,0,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,N,NaN
794,1216530,Dubai,2020-11-01,PJ Cummins,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,60.0,N,NaN
798,1216534,Dubai,2020-09-21,YS Chahal,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,N,NaN
799,1216535,Dubai,2020-10-31,Ishan Kishan,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,N,NaN
800,1216536,Dubai,2020-10-29,RD Gaikwad,Dubai International Cricket Stadium,0,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,N,NaN
803,1216539,Dubai,2020-09-25,PP Shaw,Dubai International Cricket Stadium,0,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Delhi Capitals,runs,44.0,N,NaN
806,1216542,Dubai,2020-10-08,JM Bairstow,Dubai International Cricket Stadium,0,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,N,NaN
807,1216543,Dubai,2020-10-14,A Nortje,Dubai International Cricket Stadium,0,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,N,NaN
808,1216544,Dubai,2020-10-25,RD Gaikwad,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,N,NaN
810,1216546,Dubai,2020-10-20,S Dhawan,Dubai International Cricket Stadium,0,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,Kings XI Punjab,wickets,5.0,N,NaN
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN

In [92]:
df['city'][407] = 'Bangalore'

C:\Users\user\AppData\Local\Temp\ipykernel_7732\2822321762.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][407] = 'Bangalore'

In [ ]:
df.head(2)

In [93]:
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df.isnull().sum()

In [ ]:
df = df.dropna(subset=['player_of_match'])

df

In [94]:
df.isnull().sum()

id                   0
city                 0
date                 0
player_of_match      4
venue                0
neutral_venue        0
team1                0
team2                0
toss_winner          0
toss_decision        0
winner               4
result               4
result_margin       17
eliminator           4
method             797
dtype: int64

In [ ]:
df['method'].unique()

In [ ]:
df['result_margin'].unique()

In [ ]:
df["city"].value_counts()

In [95]:
df["player_of_match"].value_counts().head(3)

player_of_match
AB de Villiers    23
CH Gayle          22
RG Sharma         18
Name: count, dtype: int64

In [ ]:
df['city'] = df['city'].replace('Bengaluru', 'Bangalore')

In [ ]:
df["city"].value_counts()

In [ ]:
#rename any column name

df = df.rename(columns={'city':'City'})
df

In [ ]:
#sum

df['result_margin'].sum()

In [96]:
# average


df['result_margin'].mean()

17.321652065081352

In [97]:
df.groupby('team1')['player_of_match'].value_counts()

team1                player_of_match
Chennai Super Kings  SK Raina           8
                     MS Dhoni           7
                     RA Jadeja          6
                     MEK Hussey         6
                     SR Watson          4
                                       ..
Sunrisers Hyderabad  JD Unadkat         1
                     JP Duminy          1
                     KK Ahmed           1
                     KMA Paul           1
                     Yuvraj Singh       1
Name: count, Length: 536, dtype: int64